### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by carlos-adir** [harrywang/tailpages#3]
I found that there are some broken links:
* [LaTeX Cheatsheet](http://harrywang.me/2022/02/09/latex-cheatsheet.html)
* [Tailpages tutorial](http://harrywang.me/tailpages/2022/01/12/tailpages-tutorial-technical.html)

I thought if it should be these links
* [LaTeX](https://harrywang.me/tailpages/2022/02/09/latex.html)
* [Code Highlight](https://harrywang.me/tailpages/2022/02/07/code.html)

**Comment by harrywang** [comment]
@carlos-adir Thanks a lot. I just fixed them. :)
